# require sudo permission
sudo: required

services:
  - docker

before_install:
  - docker build -t sarathsprakash/docker-react -f Dockerfile.dev .

script:
  - docker run sarathsprakash/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-846732671299"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


