# require sudo permission
sudo: required

services:
  - docker

before_install:
  - docker build -t sarathsprakash/docker-react -f Dockerfile.dev .

script:
  - docker run sarathsprakash/docker-react npm run test -- --coverage

